name: Deploy GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to GitHub Pages
        run: |
          mkdir -p docs
          cp -r * docs
          # If you have a custom domain, create a CNAME file
          echo "premarketinsights.in" > docs/CNAME

      - name: Commit and push changes
        run: |
          git config --local user.email "premarketinsights@gmail.com"
          git config --local user.name "Celestiq Insights"
          git add docs
          git commit -m "Deploy to PMI"
          git push origin main
